name: water_monitor
description: A water monitoring system.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  bloc: ^8.1.0
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.16
  flutter_dotenv: ^5.0.2
  firebase_core: ^2.4.0
  firebase_database: ^10.0.7
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  rive: ^0.9.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter_native_splash:
  color: "#FFFFFF"
  image: images/flutter.png

flutter:
  uses-material-design: true
  assets:
    - animations/
    - .env
